version: "3"

services:
  app:
    image: docker-inditex-technical-test-app:latest
    build:
      context: .
    container_name: inditex-technical-test-app
    ports:
      - 8080:8080

  sonarqube:
    image: sonarqube:latest
    container_name: sonar-server
    restart: always
    ports:
      - "9000:9000" # SonarQube UI
      - "9092:9092" # SonarQube Internal port
    environment:
      SONARQUBE_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonarqube
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
    depends_on:
      - sonar-db

  sonar-db:
    image: postgres:latest
    container_name: sonar-db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
    ports:
      - "5432:5432"
    volumes:
      - sonar-db-data:/var/lib/postgresql/data

volumes:
  sonar-db-data:
